In [142]:
import numpy as np # Импортирование библиотеки numpy

In [143]:
a = np.array([2, 99, 0, -1]) # Создание массива
print(a)

[ 2 99  0 -1]


In [144]:
b = np.array([[1, -5, 32.5], [1, 2, 3]])  # Создание двумерного массива
print(b)
b.shape

[[ 1.  -5.  32.5]
 [ 1.   2.   3. ]]


(2, 3)

In [145]:
a = np.zeros((2, 4)) # Двумерный массив из нулей, размером 2 на 4
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [146]:
a = np.ones((2, 4, 4)) # Трехмерный массив из единиц размером 2 на 4 на 4
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [147]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], shape=(5, 5))

In [148]:
a.shape # Вывод формы

(2, 4, 4)

In [149]:
a = np.arange(10, 30, 2) # Создадим массив от 10 до 30 не включительно с шагом 2
print(a)

[10 12 14 16 18 20 22 24 26 28]


In [150]:
a = np.arange(10, 15, 0) # Смотрю что будет если шаг 0
print(a)

ZeroDivisionError: division by zero

In [ ]:
a = np.arange(7, 10, 0.005)
print(a)
np.set_printoptions(threshold=10, precision=3)
print(a)

[7.   7.   7.01 ... 9.98 9.99 9.99]
[7.    7.005 7.01  ... 9.985 9.99  9.995]


In [ ]:
a.shape

(600,)

In [ ]:
a.dtype # Вывод типа данных

dtype('float64')

In [ ]:
m = np.array([2, 4, 6, 8])
k = np.arange(1, 8, 2)
n = m - k # Вычитание массивов
print(n)

[1 1 1 1]


In [ ]:
n = m+k # Сложение массивов
print(n)

[ 3  7 11 15]


In [ ]:
n = m*3/k # Массив m умножеенный на 3 делится на массив k
print(n)

[6.    4.    3.6   3.429]


In [ ]:
print(n**2)  # Возводим в степень

[36.    16.    12.96  11.755]


In [ ]:
print(a)
b = np.sin(a)
print(b)
np.ceil(b)

[10 12 14 16 18 20 22 24 26 28]
[-0.544 -0.537  0.991 -0.288 -0.751  0.913 -0.009 -0.906  0.763  0.271]


array([-0., -0.,  1., -0., -0.,  1., -0., -0.,  1.,  1.])

In [ ]:
a = np.array([[1,3,5],[2,6,8]])
print(a)
np.sum(a)


[[1 3 5]
 [2 6 8]]


np.int64(25)

In [ ]:
b = a.max() # Ищем максимальный элемент массива
print(b)

8


In [ ]:
a.min(axis=1) # Ищем минимум по строкам для каждого столбца

array([1, 2])

In [ ]:
a = np.arange(2, 8)
print(a)
print(a[3:6])

[2 3 4 5 6 7]
[5 6 7]


In [ ]:
print(a[::-2])

[7 5 3]


In [155]:
import random
import numpy.random as rand
a = np.random.randint(1,100, (2, 3, 5))
print(a)

[[[35 21 98 31 44]
  [34 75 13 63 47]
  [34 91  4 20 90]]

 [[18 70  6 13 54]
  [35 21  3 57 57]
  [67 49 94 85 15]]]


In [ ]:
# Индексирование и срезы 
print(a[1, 2])
print(a[0,1,2])
print(a[0,2,[1,3]])
print(a[1, 1:3,2:3])
print(a[0,: 1, :2])

[67 49 94 85 15]
13
[91 20]
[[ 3]
 [94]]
[[35 21]]


In [183]:
a.shape

(2, 3, 5)

In [184]:
for i in a.flat:
    print(i)

35
21
98
31
44
34
75
13
63
47
34
91
4
20
90
18
70
6
13
54
35
21
3
57
57
67
49
94
85
15


In [ ]:
b = a.transpose() # Транспонирование матрицы
print(b)
b.shape

[[[35 18]
  [34 35]
  [34 67]]

 [[21 70]
  [75 21]
  [91 49]]

 [[98  6]
  [13  3]
  [ 4 94]]

 [[31 13]
  [63 57]
  [20 85]]

 [[44 54]
  [47 57]
  [90 15]]]


(5, 3, 2)

In [ ]:
a = np.random.randint(1,100, (2, 2))
print(a)

[[48 70]
 [89 41]]


In [188]:
b = np.random.randint(1,100, (2, 2))
print(b)

[[42 29]
 [75 88]]


In [ ]:
np.vstack((a,b)) # Вертикальное объединение массивов

array([[48, 70],
       [89, 41],
       [42, 29],
       [75, 88]], dtype=int32)

In [ ]:
c = np.hstack((a,b)) # Горизонтальное объединение массивов
print(c)

[[48 70 42 29]
 [89 41 75 88]]


In [ ]:
np.mean(c) # Среднее значение

np.float64(60.25)

In [ ]:
np.hsplit(c,(1,2)) # Разрезать c после 1 и 2 столбца

[array([[48],
        [89]], dtype=int32),
 array([[70],
        [41]], dtype=int32),
 array([[42, 29],
        [75, 88]], dtype=int32)]

In [ ]:
print(a*b) #Перeмножили массивы a и b

[[2016 2030]
 [6675 3608]]
